baseURL = "https://iptracej-education.github.io/"
languageCode = "en-us"
title = "Kiyoshi Watanabe's Blogs"
theme = "PaperMod"
defaultContentLanguage = "en"
enableInlineShortcodes = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  env = "production"
  title = "Kiyoshi Watanabe's Notes"
  description = "Security blogs"
  author = "Kiyoshi Watanabe"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true
  defaultTheme = "auto"
  disableThemeToggle = false
 
 [params.homeInfoParams]
  Title = "Hi, I'm Kiyoshi ğŸ‘‹"
  Content = """Welcome to my blogs. I'm sharing ideas, thoughts and techniques from my work and learning. <br><br>

  - ğŸ’¼ AI/ML Engineering notes
  - ğŸ” LLM Base Software Vulnerability Discovery techniques
  - âœï¸ Writing on Qiita and Note
  - ğŸ“¬ Reach out via [LinkedIn](https://linkedin.com/in/kiyoshi-watanabe-06395213) or [email](mailto:kiwatana@hotmail.co.jp)
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/iptracej-education"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/iptracej"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/kiyoshi-watanabe-06395213/"

[[params.socialIcons]]
name = "email"
url = "mailto:kiwatana@hotmail.co.jp"

[[params.socialIcons]]
name = "medium"
url = "https://medium.com/@kiwatana"

[[params.socialIcons]]
name = "external"
url = "https://note.com/kiwatana"
title = "ğŸ—’ note"

[[params.socialIcons]]
name = "external"
url = "https://qiita.com/iptracej"
title = "ğŸ“ Qiita"


[menu]
  [[menu.main]]
  name = "Archive"
  url = "archives/"
  weight = 1

  [[menu.main]]
  name = "Search"
  url = "search/"
  weight = 2

  [[menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 3

  [[menu.main]]
  name = "Wiki"
  url = "wiki/"
  weight = 4